name: astro1
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^1.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
    - packages/astro1/assets/images/7_51.png
    - packages/astro1/assets/images/7_54.png
    - packages/astro1/assets/images/7_55.png
    - packages/astro1/assets/images/7_56.png
    - packages/astro1/assets/images/7_83.png
    - packages/astro1/assets/images/7_86.png
    - packages/astro1/assets/images/7_87.png
    - packages/astro1/assets/images/7_88.png
    - packages/astro1/assets/images/7_100.png
    - packages/astro1/assets/images/7_104.png
    - packages/astro1/assets/images/7_130.png
    - packages/astro1/assets/images/7_134.png
    - packages/astro1/assets/images/7_138.png
    - packages/astro1/assets/images/7_142.png
